$PSScriptRoot/install_browsers.ps1
$PSScriptRoot/install_encryption.ps1
$PSScriptRoot/install_auth.ps1
$PSScriptRoot/install_utility.ps1
$PSScriptRoot/install_developer.ps1
$PSScriptRoot/install_media.ps1
$PSScriptRoot/install_social.ps1
$PSScriptRoot/install_games.ps1
$PSScriptRoot/install_3d.ps1
$PSScriptRoot/install_logitech_drivers.ps1
